---
title: "Research"
bibliography: references.bib
csl: ieee.csl
reference-section-title: false  # <--- Hides the "References" header
nocite: |
  @*
---

My research spans various areas of theoretical computer science.

In **cryptography**, I currently focus on both foundations and the design of efficient **Zero-Knowledge Proofs**.

In **computational complexity**, I am particularly interested in understanding the complexity class **TFNP** of total NP search problems.

A significant part of my work explores the bridge between **game theory** and cryptography, designing and analysing protocols with **security against utility-maximizing agents**.

### Preprints

* M. Balko, J. Grebík, P. Hubáček, M. Koutecký, M. Kripner, V. Rozhoň, R. Šámal, and A. Zámečník\
"[Bolzano: Case Studies in LLM-Assisted Mathematical Research](https://arxiv.org/abs/2604.16989)"
* P. Hubáček\
"[Black-Box PWPP Is Not Turing-Closed](http://arxiv.org/abs/2602.23809)" 
* P. Chmel, P. Hubáček, and D. Stejskal\
"[Knowledge Soundness of Polynomial Commitments in the Algebraic Group Model Does Not Guarantee Extractability](https://eprint.iacr.org/2026/284)" 
* J. Belohorec, P. Hubáček, and D. Stejskal\
"[On Lifting AGM Security to AGM with Oblivious Sampling](https://eprint.iacr.org/2026/201)" 

### Publications
::: {#refs} 
:::